# Generated by Django 4.2.27 on 2026-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Doctor', max_length=20),
            preserve_default=False,
        ),
    ]
