# Generated by Django 6.0.1 on 2026-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician'), ('Accountant', 'Accountant'), ('Triage Nurse', 'Triage Nurse'), ('Radiographer', 'Radiographer')], max_length=20),
        ),
    ]
