# Generated by Django 4.2.27 on 2026-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician'), ('Accountant', 'Accountant'), ('Triage Nurse', 'Triage Nurse'), ('Radiographer', 'Radiographer'), ('Procurement Officer', 'Procurement Officer'), ('SHA Manager', 'SHA Manager')], max_length=20),
        ),
    ]
