# Generated by Django 4.2.27 on 2026-01-28 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('scheme', models.CharField(choices=[('CASH_PAYERS', 'Cash Payers'), ('INSURANCE', 'Insurance'), ('NHIF', 'NHIF')], default='CASH_PAYERS', max_length=20)),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('physical_address', models.TextField()),
                ('residence', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Kenyan', max_length=100)),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=200)),
                ('cause_of_death', models.TextField()),
                ('date_time_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('storage_area', models.CharField(choices=[('MAIN_MORGUE', 'Main Morgue'), ('TEMPORARY', 'Temporary Storage'), ('EMERGENCY', 'Emergency Storage')], max_length=20)),
                ('storage_chamber', models.CharField(choices=[('CHAMBER_A', 'Chamber A'), ('CHAMBER_B', 'Chamber B'), ('CHAMBER_C', 'Chamber C'), ('CHAMBER_D', 'Chamber D'), ('CHAMBER_E', 'Chamber E'), ('CHAMBER_F', 'Chamber F')], max_length=20)),
                ('expected_removal_date', models.DateField()),
                ('tag', models.CharField(help_text='Unique identification tag for the deceased', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_released', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deceased',
                'verbose_name_plural': 'Deceased',
                'ordering': ['-date_time_received'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('UNCLE_AUNT', 'Uncle/Aunt'), ('COUSIN', 'Cousin'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='morgue.deceased')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MorgueAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMITTED', 'Admitted'), ('RELEASED', 'Released'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=20)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('released_to', models.CharField(blank=True, help_text='Person/organization released to', max_length=200)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='morgue.deceased')),
            ],
            options={
                'verbose_name': 'Morgue Admission',
                'verbose_name_plural': 'Morgue Admissions',
                'ordering': ['-admission_date'],
            },
        ),
    ]
