# Generated by Django 4.2.27 on 2026-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deceased',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deceased', 'verbose_name_plural': 'Deceased'},
        ),
        migrations.AlterModelOptions(
            name='morgueadmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Morgue Admission', 'verbose_name_plural': 'Morgue Admissions'},
        ),
        migrations.RemoveField(
            model_name='deceased',
            name='date_time_received',
        ),
        migrations.RemoveField(
            model_name='morgueadmission',
            name='admission_date',
        ),
        migrations.AlterField(
            model_name='morgueadmission',
            name='status',
            field=models.CharField(choices=[('ADMITTED', 'Admitted'), ('RELEASED', 'Released'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=20),
        ),
    ]
