# Generated by Django 4.2.27 on 2026-01-28 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0002_alter_deceased_options_alter_morgueadmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morgueadmission',
            options={'ordering': ['-admission_datetime'], 'verbose_name': 'Morgue Admission', 'verbose_name_plural': 'Morgue Admissions'},
        ),
        migrations.AddField(
            model_name='deceased',
            name='time_of_death',
            field=models.TimeField(default=datetime.datetime(2026, 1, 28, 9, 47, 54, 61296, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morgueadmission',
            name='admission_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 9, 48, 11, 442536, tzinfo=datetime.timezone.utc), help_text='Date and time when deceased was admitted to morgue'),
            preserve_default=False,
        ),
    ]
