# Generated by Django 6.0.1 on 2026-01-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mortuaryservice'),
        ('morgue', '0003_alter_morgueadmission_options_deceased_time_of_death_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformedMortuaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_services', to='morgue.deceased')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morgue_services_performed', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morgue_placements', to='accounts.mortuaryservice')),
            ],
            options={
                'verbose_name': 'Performed Mortuary Service',
                'verbose_name_plural': 'Performed Mortuary Services',
                'ordering': ['-date_performed'],
            },
        ),
    ]
