# Generated by Django 6.0.1 on 2026-01-28 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0004_performedmortuaryservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortuaryDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_to', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('receiver_id_number', models.CharField(max_length=50)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('total_bill_snapshot', models.DecimalField(decimal_places=2, help_text='Total bill at time of discharge', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='morgue.morgueadmission')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morgue_discharges_authorized', to=settings.AUTH_USER_MODEL)),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_record', to='morgue.deceased')),
            ],
            options={
                'verbose_name': 'Mortuary Discharge',
                'verbose_name_plural': 'Mortuary Discharges',
            },
        ),
    ]
