# Generated by Django 6.0.1 on 2026-01-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoice_invoiceitem_payment_service'),
        ('morgue', '0005_mortuarydischarge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performedmortuaryservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morgue_placements', to='accounts.service'),
        ),
    ]
