# Generated by Django 6.0.1 on 2026-02-02 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0006_alter_performedmortuaryservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performedmortuaryservice',
            name='date_performed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
