# Generated by Django 6.0.1 on 2026-02-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0007_alter_performedmortuaryservice_date_performed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Morgue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_charge_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='deceased',
            name='storage_chamber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='morgue.chamber'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='morgue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='morgue.morgue'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='storage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='morgue.morgue'),
        ),
    ]
