# Generated by Django 6.0.1 on 2026-01-28 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_hospitalservice'),
        ('home', '0004_emergencycontact'),
        ('inventory', '0004_inventoryrequest_inventoryacknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('bed_type', models.CharField(choices=[('Normal', 'Normal'), ('Oxygen', 'Oxygen Support'), ('Ventilator', 'Ventilator'), ('Cradle', 'Cradle/Cot')], default='Normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('HDU', 'HDU'), ('Pediatric', 'Pediatric'), ('Maternity', 'Maternity'), ('Surgical', 'Surgical'), ('Emergency', 'Emergency')], default='General', max_length=20)),
                ('base_charge_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('provisional_diagnosis', models.TextField()),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('Deceased', 'Deceased')], default='Admitted', max_length=20)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('final_diagnosis', models.TextField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True, null=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_processed', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges_processed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='home.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='home.visit')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='inpatient.bed')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g., TDS, BD, QID', max_length=100)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('is_administered', models.BooleanField(default=False)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_administered', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='inpatient.admission')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_medications', to='inventory.inventoryitem')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_prescribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAdmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_provided', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='inpatient.admission')),
                ('provided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_placements', to='accounts.hospitalservice')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inpatient.ward'),
        ),
    ]
