# Generated by Django 6.0.1 on 2026-01-28 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_diagnosis', models.TextField()),
                ('discharge_summary', models.TextField()),
                ('total_bill_snapshot', models.DecimalField(decimal_places=2, help_text='Total bill at time of discharge', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_record', to='inpatient.admission')),
                ('discharged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharges_authorized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inpatient Discharge',
                'verbose_name_plural': 'Inpatient Discharges',
                'ordering': ['-discharge_date'],
            },
        ),
    ]
