# Generated by Django 4.2.27 on 2026-01-29 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inpatient', '0003_alter_serviceadmissionlink_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inpatient.admission')),
                ('from_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='inpatient.bed')),
                ('to_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='inpatient.bed')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='%', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=4, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='inpatient.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_type', models.CharField(choices=[('Intake', 'Intake'), ('Output', 'Output')], max_length=10)),
                ('item', models.CharField(help_text='e.g., Normal Saline, Urine, Vomitus', max_length=100)),
                ('amount_ml', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balances', to='inpatient.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('Doctor', "Doctor's Note"), ('Nursing', 'Nursing Note'), ('Consultation', 'Consultation Note'), ('Operational', 'Operation Note')], default='Doctor', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='inpatient.admission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
