# Generated by Django 6.0.1 on 2026-01-29 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_wardtransfer_patientvitals_fluidbalance_clinicalnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('instruction_type', models.CharField(choices=[('Treatment', 'Treatment'), ('Activity', 'Activity/Mobility'), ('Monitoring', 'Monitoring'), ('General', 'General')], default='General', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='inpatient.admission')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('Full', 'Full Diet'), ('Soft', 'Soft Diet'), ('Liquid', 'Liquid Diet'), ('Diabetic', 'Diabetic Diet'), ('Renal', 'Renal Diet'), ('Low-Salt', 'Low Salt Diet'), ('NPO', 'Nil Per Os (Nothing by Mouth)')], default='Full', max_length=50)),
                ('specific_instructions', models.TextField(blank=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_orders', to='inpatient.admission')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_prescribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
