# Generated by Django 6.0.1 on 2026-02-02 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0005_doctorinstruction_nutritionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadmissionlink',
            name='date_provided',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
