# Generated by Django 4.2.27 on 2026-02-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0006_alter_serviceadmissionlink_date_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationchart',
            name='dose_count',
            field=models.PositiveIntegerField(default=1, help_text='Units per dose (e.g., 2 tablets)'),
        ),
        migrations.AddField(
            model_name='medicationchart',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Total days (e.g., 7 days)'),
        ),
        migrations.AddField(
            model_name='medicationchart',
            name='frequency_count',
            field=models.PositiveIntegerField(default=1, help_text='Times per day (e.g., 3 times)'),
        ),
        migrations.AlterField(
            model_name='medicationchart',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicationchart',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., TDS, BD, QID', max_length=100, null=True),
        ),
    ]
