# Generated by Django 4.2.27 on 2026-02-06 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inpatient', '0007_medicationchart_dose_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationchart',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationchart',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_dispensed_ipd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationchart',
            name='is_dispensed',
            field=models.BooleanField(default=False, help_text='Has this been dispensed by pharmacy?'),
        ),
        migrations.AddField(
            model_name='medicationchart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total units to dispense'),
        ),
    ]
