# Generated by Django 6.0.1 on 2026-02-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0008_medicationchart_dispensed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationchart',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='DEPRECATED - kept for old records'),
        ),
        migrations.AlterField(
            model_name='medicationchart',
            name='frequency',
            field=models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Thrice Daily', 'Thrice Daily'), ('Four Times Daily', 'Four Times Daily'), ('Every 6 Hours', 'Every 6 Hours'), ('Every 8 Hours', 'Every 8 Hours'), ('Every 12 Hours', 'Every 12 Hours'), ('Every 24 Hours', 'Every 24 Hours'), ('As Needed', 'As Needed')], default='Once Daily', help_text='Frequency of medication', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationchart',
            name='frequency_count',
            field=models.PositiveIntegerField(default=1, help_text='DEPRECATED - kept for old records'),
        ),
    ]
