# Generated by Django 6.0.1 on 2026-02-13 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0009_alter_medicationchart_duration_days_and_more'),
        ('inventory', '0012_stockrecord_purchase_ref_stockrecord_receiving_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='inpatient.admission')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_dispensed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_consumables', to='inventory.inventoryitem')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_prescribed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inpatient Consumable',
                'verbose_name_plural': 'Inpatient Consumables',
                'ordering': ['-prescribed_at'],
            },
        ),
    ]
