# Generated by Django 6.0.1 on 2026-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0010_inpatientconsumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientconsumable',
            name='instructions',
            field=models.TextField(blank=True, help_text='Specific instructions for this consumable', null=True),
        ),
        migrations.AddField(
            model_name='medicationchart',
            name='instructions',
            field=models.TextField(blank=True, help_text='Specific instructions for this medication', null=True),
        ),
    ]
