# Generated by Django 6.0.1 on 2026-02-24 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0011_inpatientconsumable_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationchart',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days the medication should be given'),
        ),
        migrations.CreateModel(
            name='MedicationAdministrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='The day number of the prescription (e.g. Day 1, Day 2)')),
                ('dose_number', models.PositiveIntegerField(help_text='The dose sequence for that day (e.g. Dose 1, Dose 2)')),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Expected time of administration', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Administered', 'Administered'), ('Missed', 'Missed')], default='Pending', max_length=20)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doses_administered', to=settings.AUTH_USER_MODEL)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_records', to='inpatient.medicationchart')),
            ],
            options={
                'verbose_name': 'MAR Entry',
                'verbose_name_plural': 'MAR Entries',
                'ordering': ['day_number', 'dose_number'],
                'unique_together': {('chart', 'day_number', 'dose_number')},
            },
        ),
    ]
