# Generated by Django 4.2.27 on 2026-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalvisit',
            name='service_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='antenatalvisit',
            name='gestational_age',
            field=models.PositiveIntegerField(blank=True, help_text='Weeks', null=True),
        ),
        migrations.AlterField(
            model_name='antenatalvisit',
            name='visit_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
