# Generated by Django 4.2.27 on 2026-01-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0002_antenatalvisit_service_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnatalbabyvisit',
            name='service_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postnatalmothervisit',
            name='service_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postnatalbabyvisit',
            name='visit_day',
            field=models.PositiveIntegerField(blank=True, help_text='Days post-delivery', null=True),
        ),
        migrations.AlterField(
            model_name='postnatalmothervisit',
            name='visit_day',
            field=models.PositiveIntegerField(blank=True, help_text='Days post-delivery', null=True),
        ),
    ]
