# Generated by Django 4.2.27 on 2026-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0003_postnatalbabyvisit_service_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='is_multiple_gestation',
            field=models.BooleanField(default=False, verbose_name='Multiple Gestation (Twins/Triplets)'),
        ),
    ]
