# Generated by Django 6.0.1 on 2026-01-30 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0004_pregnancy_is_multiple_gestation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mother_condition_at_discharge', models.CharField(choices=[('Stable', 'Healthy / Stable'), ('Needs Follow-up', 'Requires Close Follow-up'), ('Complicated', 'Complicated Recovery')], default='Stable', max_length=50)),
                ('baby_condition_at_discharge', models.CharField(help_text='Summary of newborn(s) status', max_length=100)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(help_text='Clinical summary of the maternity episode')),
                ('follow_up_plan', models.TextField(help_text='Instructions for postnatal care and return visits')),
                ('medications_prescribed', models.TextField(blank=True, help_text='Medications given to take home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_discharges_authorized', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maternity_discharge', to='maternity.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='MaternityReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('referred_to_facility', models.CharField(help_text='Name of the receiving hospital', max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('reason_for_referral', models.TextField()),
                ('clinical_clinical_summary', models.TextField(help_text='Clinical status and interventions performed')),
                ('urgent', models.BooleanField(default=False)),
                ('transport_mode', models.CharField(choices=[('Ambulance', 'Ambulance'), ('Private', 'Private Means'), ('Public', 'Public Transport')], default='Ambulance', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='maternity.pregnancy')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
