# Generated by Django 4.2.27 on 2026-01-30 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maternity', '0005_maternitydischarge_maternityreferral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(help_text='e.g., BCG, OPV, DPT', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_diseases', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, help_text='Oral, Intramuscular, etc.', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(default=1, help_text='1st Dose, 2nd Dose, Booster, etc.')),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('weight_at_vaccination', models.DecimalField(blank=True, decimal_places=3, help_text='kg', max_digits=5, null=True)),
                ('reaction_observed', models.TextField(blank=True, help_text='Any adverse reactions')),
                ('next_dose_due', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, help_text='Facility where vaccine was given', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('newborn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='maternity.newborn')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternity.vaccine')),
            ],
            options={
                'verbose_name': 'Immunization Record',
                'verbose_name_plural': 'Immunization Records',
                'ordering': ['-date_administered'],
                'unique_together': {('newborn', 'vaccine', 'dose_number')},
            },
        ),
    ]
