# Generated by Django 4.2.27 on 2026-01-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0006_vaccine_immunizationrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizationrecord',
            name='weight_at_vaccination',
        ),
        migrations.AddField(
            model_name='immunizationrecord',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='maternity.postnatalbabyvisit'),
        ),
    ]
