# Generated by Django 4.2.27 on 2026-02-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_patient_id_number'),
        ('maternity', '0007_remove_immunizationrecord_weight_at_vaccination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn',
            name='patient_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newborn_clinical_record', to='home.patient'),
        ),
    ]
