# Generated by Django 6.0.1 on 2026-02-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_referral'),
        ('maternity', '0008_newborn_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='home.patient'),
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='newborn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='maternity.newborn'),
        ),
    ]
