# Generated by Django 6.0.1 on 2026-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0009_immunizationrecord_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalvisit',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Whether this visit record is complete/closed'),
        ),
    ]
