# Generated by Django 6.0.1 on 2026-02-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_referral'),
        ('maternity', '0010_antenatalvisit_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='labordelivery',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_delivery', to='home.visit'),
        ),
    ]
