# Generated by Django 6.0.1 on 2026-02-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_referral'),
        ('maternity', '0011_labordelivery_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalvisit',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_anc_visits', to='home.visit'),
        ),
        migrations.AddField(
            model_name='postnatalbabyvisit',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_baby_pnc_visits', to='home.visit'),
        ),
        migrations.AddField(
            model_name='postnatalmothervisit',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_mother_pnc_visits', to='home.visit'),
        ),
    ]
