"""MOH 705B — Diseases (new cases) and attendance rows."""

# category: disease | attendance | referral | other
MOH705B_LINES = [
    {'row_key': 'd01', 'line_number': 1, 'disease_name': 'Diarrhoea', 'category': 'disease'},
    {'row_key': 'd02', 'line_number': 2, 'disease_name': 'Tuberculosis', 'category': 'disease'},
    {'row_key': 'd03', 'line_number': 3, 'disease_name': 'Dysentry (Bloody diarrhoea)', 'category': 'disease'},
    {'row_key': 'd04', 'line_number': 4, 'disease_name': 'Cholera', 'category': 'disease'},
    {'row_key': 'd05', 'line_number': 5, 'disease_name': 'Meningococcal Meningitis', 'category': 'disease'},
    {'row_key': 'd06', 'line_number': 6, 'disease_name': 'Other Meningitis', 'category': 'disease'},
    {'row_key': 'd07', 'line_number': 7, 'disease_name': 'Tetanus', 'category': 'disease'},
    {'row_key': 'd08', 'line_number': 8, 'disease_name': 'Poliomyelitis (AFP)', 'category': 'disease'},
    {'row_key': 'd09', 'line_number': 9, 'disease_name': 'Chicken Pox', 'category': 'disease'},
    {'row_key': 'd10', 'line_number': 10, 'disease_name': 'Measles', 'category': 'disease'},
    {'row_key': 'd11', 'line_number': 11, 'disease_name': 'Hepatitis', 'category': 'disease'},
    {'row_key': 'd12', 'line_number': 12, 'disease_name': 'Mumps', 'category': 'disease'},
    {'row_key': 'd13', 'line_number': 13, 'disease_name': 'Suspected Malaria', 'category': 'disease'},
    {'row_key': 'd14', 'line_number': 14, 'disease_name': 'Confirmed Malaria', 'category': 'disease'},
    {'row_key': 'd15', 'line_number': 15, 'disease_name': 'Malaria in Pregnancy', 'category': 'disease'},
    {'row_key': 'd16', 'line_number': 16, 'disease_name': 'Amoebiasis', 'category': 'disease'},
    {'row_key': 'd17', 'line_number': 17, 'disease_name': 'Typhoid fever', 'category': 'disease'},
    {'row_key': 'd18', 'line_number': 18, 'disease_name': 'Sexually Transmitted Infections', 'category': 'disease'},
    {'row_key': 'd19', 'line_number': 19, 'disease_name': 'Urinary Tract Infections', 'category': 'disease'},
    {'row_key': 'd20', 'line_number': 20, 'disease_name': 'Bilharzia (Schistosomiasis)', 'category': 'disease'},
    {'row_key': 'd21', 'line_number': 21, 'disease_name': 'Intestinal worms', 'category': 'disease'},
    {'row_key': 'd22', 'line_number': 22, 'disease_name': 'Malnutrition', 'category': 'disease'},
    {'row_key': 'd23', 'line_number': 23, 'disease_name': 'Anaemia', 'category': 'disease'},
    {'row_key': 'd24', 'line_number': 24, 'disease_name': 'Eye Infections/Conditions', 'category': 'disease'},
    {'row_key': 'd25', 'line_number': 25, 'disease_name': 'Ear Infections/Conditions', 'category': 'disease'},
    {'row_key': 'd26', 'line_number': 26, 'disease_name': 'Upper Respiratory Tract Infections', 'category': 'disease'},
    {'row_key': 'd27', 'line_number': 27, 'disease_name': 'Asthma', 'category': 'disease'},
    {'row_key': 'd28', 'line_number': 28, 'disease_name': 'Pneumonia', 'category': 'disease'},
    {'row_key': 'd29', 'line_number': 29, 'disease_name': 'Other Lower Respiratory tract infections', 'category': 'disease'},
    {'row_key': 'd30', 'line_number': 30, 'disease_name': 'Abortion', 'category': 'disease'},
    {'row_key': 'd31', 'line_number': 31, 'disease_name': 'Dis. of Puerperium & Childbirth', 'category': 'disease'},
    {'row_key': 'd32', 'line_number': 32, 'disease_name': 'Hypertension', 'category': 'disease'},
    {'row_key': 'd33', 'line_number': 33, 'disease_name': 'Mental Disorders', 'category': 'disease'},
    {'row_key': 'd34', 'line_number': 34, 'disease_name': 'Dental Disorders', 'category': 'disease'},
    {'row_key': 'd35', 'line_number': 35, 'disease_name': 'Jiggers Infestation', 'category': 'disease'},
    {'row_key': 'd36', 'line_number': 36, 'disease_name': 'Diseases of the skin', 'category': 'disease'},
    {'row_key': 'd37', 'line_number': 37, 'disease_name': 'Arthritis, Joint pains etc.', 'category': 'disease'},
    {'row_key': 'd38', 'line_number': 38, 'disease_name': 'Poisoning', 'category': 'disease'},
    {'row_key': 'd39', 'line_number': 39, 'disease_name': 'Road Traffic Injuries', 'category': 'disease'},
    {'row_key': 'd40', 'line_number': 40, 'disease_name': 'Deaths due to Road Traffic Injuries', 'category': 'disease'},
    {'row_key': 'd41', 'line_number': 41, 'disease_name': 'Other injuries', 'category': 'disease'},
    {'row_key': 'd42', 'line_number': 42, 'disease_name': 'Sexual Violence', 'category': 'disease'},
    {'row_key': 'd43', 'line_number': 43, 'disease_name': 'Violence related injuries', 'category': 'disease'},
    {'row_key': 'd44', 'line_number': 44, 'disease_name': 'Burns', 'category': 'disease'},
    {'row_key': 'd45', 'line_number': 45, 'disease_name': 'Snake Bites', 'category': 'disease'},
    {'row_key': 'd46', 'line_number': 46, 'disease_name': 'Dog Bites', 'category': 'disease'},
    {'row_key': 'd47', 'line_number': 47, 'disease_name': 'Other Bites', 'category': 'disease'},
    {'row_key': 'd48', 'line_number': 48, 'disease_name': 'Diabetes', 'category': 'disease'},
    {'row_key': 'd49', 'line_number': 49, 'disease_name': 'Epilepsy', 'category': 'disease'},
    {'row_key': 'd50', 'line_number': 50, 'disease_name': 'Brucellosis', 'category': 'disease'},
    {'row_key': 'd51', 'line_number': 51, 'disease_name': 'Cardiovascular conditions', 'category': 'disease'},
    {'row_key': 'd52', 'line_number': 52, 'disease_name': 'Central Nervous System Conditions', 'category': 'disease'},
    {'row_key': 'd53', 'line_number': 53, 'disease_name': 'Overweight (BMI >25)', 'category': 'disease'},
    {'row_key': 'd54', 'line_number': 54, 'disease_name': 'Muscular skeletal conditions', 'category': 'disease'},
    {'row_key': 'd55', 'line_number': 55, 'disease_name': 'Fistula (Birth related)', 'category': 'disease'},
    {'row_key': 'd56', 'line_number': 56, 'disease_name': 'Suspected Neoplasms/Cancers', 'category': 'disease'},
    {'row_key': 'd57', 'line_number': 57, 'disease_name': 'Physical Disability', 'category': 'disease'},
    {'row_key': 'd58', 'line_number': 58, 'disease_name': 'Trypanosomiasis', 'category': 'disease'},
    {'row_key': 'd59', 'line_number': 59, 'disease_name': 'Rift valley fever', 'category': 'disease'},
    {'row_key': 'd60', 'line_number': 60, 'disease_name': 'Yellow Fever', 'category': 'disease'},
    {'row_key': 'd61', 'line_number': 61, 'disease_name': 'Viral Haemorrhagic Fever', 'category': 'disease'},
    {'row_key': 'd62', 'line_number': 62, 'disease_name': 'Chikungunya', 'category': 'disease'},
    {'row_key': 'd63', 'line_number': 63, 'disease_name': 'Dengue fever', 'category': 'disease'},
    {'row_key': 'd64', 'line_number': 64, 'disease_name': 'Leishmaniasis (Kala-azar)', 'category': 'disease'},
    {'row_key': 'd65', 'line_number': 65, 'disease_name': 'Cutaneous leishmaniasis', 'category': 'disease'},
    {'row_key': 'd66', 'line_number': 66, 'disease_name': 'Suspected Anthrax', 'category': 'disease'},
    {'row_key': 'd67', 'line_number': 67, 'disease_name': 'ALL OTHER DISEASES', 'category': 'disease'},
    {'row_key': 'd68', 'line_number': 68, 'disease_name': 'Tested for Malaria', 'category': 'other'},
    {'row_key': 'd69', 'line_number': 69, 'disease_name': '', 'category': 'spacer'},
    {'row_key': 'd70', 'line_number': 70, 'disease_name': '', 'category': 'spacer'},
    {'row_key': 'd71', 'line_number': 71, 'disease_name': 'NO. OF FIRST ATTENDANCES', 'category': 'attendance'},
    {'row_key': 'd72', 'line_number': 72, 'disease_name': 'RE-ATTENDANCES', 'category': 'attendance'},
    {'row_key': 'd73', 'line_number': 73, 'disease_name': 'Referrals from other health facility', 'category': 'referral'},
    {'row_key': 'd74', 'line_number': 74, 'disease_name': 'Referrals to other health facility', 'category': 'referral'},
    {'row_key': 'd75', 'line_number': 75, 'disease_name': 'Referrals from community unit', 'category': 'referral'},
    {'row_key': 'd76', 'line_number': 76, 'disease_name': 'Referrals to community unit', 'category': 'referral'},
]
