# Generated by Django 4.2.27 on 2026-01-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Imaging', 'Imaging'), ('Lab Test', 'Lab Test'), ('Endoscopy', 'Endoscopy'), ('Physiological Test', 'Physiological Test'), ('Other', 'Other')], default='Lab Test', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='patientserviceinvoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicaltestservice'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
