# Generated by Django 4.2.27 on 2026-01-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_medicaltestservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientserviceinvoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
