# Generated by Django 6.0.1 on 2026-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientserviceinvoice_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Nursing', 'Nursing Care'), ('Oxygen', 'Oxygen Therapy'), ('Consultation', 'Consultation'), ('Procedure', 'Procedure'), ('Equipment', 'Equipment Usage'), ('Accommodation', 'Accommodation'), ('Other', 'Other Services')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
