# Generated by Django 6.0.1 on 2026-01-29 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mpesapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Payment'), ('Partial', 'Partially Paid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Snapshot of item name at time of invoice creation', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at moment of sale', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Insurance', 'Insurance'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='M-Pesa Receipt Number, Insurance Claim ID, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Consultation', 'Consultation'), ('Lab', 'Laboratory'), ('Imaging', 'Imaging/Radiology'), ('Procedure', 'Procedure'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing Care'), ('Antenatal', 'Antenatal Care'), ('Surgery', 'Surgery'), ('Admission', 'Admission/Accommodation'), ('Mortuary', 'Mortuary'), ('Other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
