# Generated by Django 6.0.1 on 2026-01-29 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoice_invoiceitem_payment_service'),
        ('home', '0005_triageentry_height_triageentry_weight'),
        ('inpatient', '0003_alter_serviceadmissionlink_service'),
        ('inventory', '0004_inventoryrequest_inventoryacknowledgement'),
        ('lab', '0002_alter_labresult_invoice_alter_labresult_service'),
        ('morgue', '0006_alter_performedmortuaryservice_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalService',
        ),
        migrations.RemoveField(
            model_name='patientserviceinvoice',
            name='service',
        ),
        migrations.DeleteModel(
            name='MortuaryService',
        ),
        migrations.RemoveField(
            model_name='patientserviceinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientserviceinvoice',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='mpesapayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'M-Pesa Transaction Log', 'verbose_name_plural': 'M-Pesa Transaction Logs'},
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='home.patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='home.visit'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.invoice'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_log', to='accounts.payment'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.service'),
        ),
        migrations.DeleteModel(
            name='MedicalTestService',
        ),
        migrations.DeleteModel(
            name='PatientServiceInvoice',
        ),
    ]
