# Generated by Django 6.0.1 on 2026-01-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_hospitalservice_and_more'),
        ('home', '0005_triageentry_height_triageentry_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['department__name', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='home.departments'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Lab', 'Laboratory'), ('Imaging', 'Imaging/Radiology'), ('Procedure', 'Procedure'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing Care'), ('Antenatal', 'Antenatal Care'), ('Surgery', 'Surgery'), ('Admission', 'Admission/Accommodation'), ('Mortuary', 'Mortuary'), ('Other', 'Other')], help_text='Legacy field - use department instead', max_length=50, null=True),
        ),
    ]
