# Generated by Django 4.2.27 on 2026-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_service_options_service_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or reference information', null=True),
        ),
    ]
