# Generated by Django 4.2.27 on 2026-01-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0006_alter_performedmortuaryservice_service'),
        ('home', '0006_prescription_prescriptionitem'),
        ('accounts', '0010_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deceased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='morgue.deceased'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='home.patient'),
        ),
    ]
