# Generated by Django 4.2.27 on 2026-02-01 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockadjustment_adjusted_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_expensecategory_expense_inventorypurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='supplier_invoices/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventorypurchase',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Goods Received Note', 'verbose_name_plural': 'Goods Received Notes'},
        ),
        migrations.RemoveField(
            model_name='inventorypurchase',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='inventorypurchase',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='inventorypurchase',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='inventorypurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total value of items received', max_digits=12),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.supplierinvoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventorypurchase',
            name='invoice_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='accounts.supplierinvoice'),
        ),
    ]
