# Generated by Django 6.0.1 on 2026-02-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_supplierinvoice_alter_inventorypurchase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('ranges', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.service')),
            ],
        ),
    ]
