# Generated by Django 6.0.1 on 2026-02-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_procedure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='department',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.procedure'),
        ),
    ]
