# Generated by Django 6.0.1 on 2026-02-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_procedure_options_remove_procedure_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='procedure',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
