# Generated by Django 6.0.1 on 2026-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_invoiceitem_procedure_delete_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
