# Generated by Django 6.0.1 on 2026-02-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_invoiceitem_paid_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceParameters',
        ),
    ]
