# Generated by Django 6.0.1 on 2026-02-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_backfill_grn_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='insurance_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Per-diem shortfall absorbed by facility for insurance patients', max_digits=12),
        ),
    ]
