# Generated by Django 6.0.1 on 2026-02-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_invoice_insurance_adjustment'),
        ('home', '0014_referral'),
        ('morgue', '0007_alter_performedmortuaryservice_date_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deceased',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='morgue.deceased'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='home.visit'),
        ),
    ]
