"""
Django settings for hms project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+7azj(_fpsjzgc14%a0*4umus-ueczyi0hb63t_b3u!0d%u9-1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['127.0.0.1','192.168.1.40', 'localhost']

if os.getenv('ALLOWED_HOSTS'):
    ALLOWED_HOSTS.extend(os.getenv('ALLOWED_HOSTS').split(','))
CSRF_TRUSTED_ORIGINS = [
    'https://arhythmically-unciliated-danna.ngrok-free.dev',
]
# Custom user model
AUTH_USER_MODEL = 'users.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'channels',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'home',
    'accounts',
    'morgue',
    'inventory',
    'inpatient',
    'lab',
    'maternity',
    'comms',
    'reports.apps.ReportsConfig',
    'hr',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'hms.middleware.LicenseVerificationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hms.urls'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'users' / 'static',
    BASE_DIR / 'home' / 'static',
    BASE_DIR / 'accounts' / 'static',
    BASE_DIR / 'morgue' / 'static',
    BASE_DIR / 'inventory' / 'static',
    BASE_DIR / 'inpatient' / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'reports', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hr.context_processors.hr_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'hms.wsgi.application'
ASGI_APPLICATION = 'hms.asgi.application'

# Channel Layers (using Redis for production/real-time signaling)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv('ENVIRONMENT') == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Authentication URLs
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'users:dashboard'
LOGOUT_REDIRECT_URL = 'users:login'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# Session Timeout (4 hours of inactivity)
SESSION_COOKIE_AGE = 14400  
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SHA / DHA HIE integration settings (AfyaLink)
SHA_HIE_BASE_URL = os.getenv('SHA_HIE_BASE_URL', 'https://uat.dha.go.ke')
SHA_HIE_USERNAME = os.getenv('SHA_HIE_USERNAME', '')
SHA_HIE_PASSWORD = os.getenv('SHA_HIE_PASSWORD', '')
# Agent ID (Basic Auth section) + Token Auth Key/Secret from DHA portal.
SHA_HIE_AGENT_ID = os.getenv('SHA_HIE_AGENT_ID', '')
SHA_HIE_CONSUMER_KEY = os.getenv('SHA_HIE_CONSUMER_KEY', '')
SHA_HIE_CONSUMER_SECRET = os.getenv('SHA_HIE_CONSUMER_SECRET', '')
SHA_HIE_TIMEOUT_SECONDS = int(os.getenv('SHA_HIE_TIMEOUT_SECONDS', '45'))
SHA_HIE_VERIFY_SSL = os.getenv('SHA_HIE_VERIFY_SSL', 'true').lower() == 'true'
SHA_HIE_TOKEN_PATH = os.getenv('SHA_HIE_TOKEN_PATH', '/v1/hie-auth')
SHA_HIE_CLIENT_VERIFY_PATH = os.getenv(
    'SHA_HIE_CLIENT_VERIFY_PATH',
    '/v3/client-registry/fetch-client',
)
SHA_HIE_ELIGIBILITY_PATH = os.getenv(
    'SHA_HIE_ELIGIBILITY_PATH',
    '/v2/eligibility',
)
SHA_HIE_FACILITY_SEARCH_PATH = os.getenv(
    'SHA_HIE_FACILITY_SEARCH_PATH',
    '/v2/facility-search',
)
# DHA Terminology Service — ICD-11 validate/search (AfyaLink / ILM middleware)
# Auth still uses SHA_HIE_BASE_URL (/v1/hie-auth); terminology routes live on the middleware host.
SHA_HIE_TERMINOLOGY_BASE_URL = os.getenv(
    'SHA_HIE_TERMINOLOGY_BASE_URL',
    'https://ilm-dev.dha.go.ke/uat-middleware/api/v1',
)
SHA_HIE_ICD11_SEARCH_PATH = os.getenv(
    'SHA_HIE_ICD11_SEARCH_PATH',
    '/clinical/concepts',
)
SHA_HIE_ICD11_OWNER = os.getenv('SHA_HIE_ICD11_OWNER', 'WHO')
SHA_HIE_ICD11_SOURCE = os.getenv('SHA_HIE_ICD11_SOURCE', 'ICD-11')
# DHA HPT (Health Products & Technologies) — PPB generic/product concepts for eRx
SHA_HIE_HPT_OWNER = os.getenv('SHA_HIE_HPT_OWNER', 'MOH-PPB')
SHA_HIE_HPT_SOURCE = os.getenv('SHA_HIE_HPT_SOURCE', 'HPT')
# On prescribe: suggest/require DHA generic_concept_code (GE*) after local drug select
HPT_DHA_SUGGEST_ON_SELECT = os.getenv('HPT_DHA_SUGGEST_ON_SELECT', 'true').lower() == 'true'
HPT_DHA_REQUIRE_CODE = os.getenv('HPT_DHA_REQUIRE_CODE', 'false').lower() == 'true'

# Facility identity for eClaims / eRx (X-Facility-Id headers)
SHA_HIE_FACILITY_FR_CODE = os.getenv('SHA_HIE_FACILITY_FR_CODE', '')
SHA_HIE_FACILITY_ID_TYPE = os.getenv('SHA_HIE_FACILITY_ID_TYPE', 'fr-code')
SHA_HIE_FACILITY_NAME = os.getenv('SHA_HIE_FACILITY_NAME', '')
SHA_HIE_DEFAULT_INTERVENTION_OPD = os.getenv('SHA_HIE_DEFAULT_INTERVENTION_OPD', 'SHA-18-005')
SHA_HIE_DEFAULT_INTERVENTION_IPD = os.getenv('SHA_HIE_DEFAULT_INTERVENTION_IPD', 'SHA-11-001')
# When true, insurance desk also pushes claim submit to DHA after local payment
SHA_HIE_AUTO_SUBMIT_ON_INSURANCE = os.getenv('SHA_HIE_AUTO_SUBMIT_ON_INSURANCE', 'false').lower() == 'true'

# Clinical Summary / Shared Encounter (Kenya HIE)
SHA_HIE_CLINICAL_FHIR_BUNDLE_PATH = os.getenv(
    'SHA_HIE_CLINICAL_FHIR_BUNDLE_PATH',
    '/clinical/fhir/bundle',
)
SHA_HIE_ENCOUNTER_SYNC_PATH = os.getenv(
    'SHA_HIE_ENCOUNTER_SYNC_PATH',
    '/api/v1/encounter/sync',
)

# WHO ICD-11 API (https://icd.who.int/docs/icd-api/APIDoc-Version2/)
ICD11_API_BASE_URL = os.getenv('ICD11_API_BASE_URL', 'https://id.who.int')
ICD11_TOKEN_URL = os.getenv(
    'ICD11_TOKEN_URL',
    'https://icdaccessmanagement.who.int/connect/token',
)
ICD11_CLIENT_ID = os.getenv('ICD11_CLIENT_ID', '')
ICD11_CLIENT_SECRET = os.getenv('ICD11_CLIENT_SECRET', '')
ICD11_RELEASE = os.getenv('ICD11_RELEASE', '2024-01')
ICD11_LINEARIZATION = os.getenv('ICD11_LINEARIZATION', 'mms')
ICD11_LANGUAGE = os.getenv('ICD11_LANGUAGE', 'en')
ICD11_TIMEOUT_SECONDS = int(os.getenv('ICD11_TIMEOUT_SECONDS', '20'))
ICD11_VERIFY_SSL = os.getenv('ICD11_VERIFY_SSL', 'true').lower() == 'true'
ICD11_USE_LOCAL_DB = os.getenv('ICD11_USE_LOCAL_DB', 'true').lower() == 'true'
# On select: search local DB, then cross-check code+title with DHA terminology API
ICD11_DHA_VALIDATE_ON_SELECT = os.getenv('ICD11_DHA_VALIDATE_ON_SELECT', 'true').lower() == 'true'
# If true, reject selection when DHA is unreachable; if false, allow with warning
ICD11_DHA_VALIDATE_STRICT = os.getenv('ICD11_DHA_VALIDATE_STRICT', 'false').lower() == 'true'
ICD11_TABULATION_URL = os.getenv(
    'ICD11_TABULATION_URL',
    'https://icdcdn.who.int/static/releasefiles/{release}/SimpleTabulation-ICD-11-MMS-{language}.zip',
)
