# Generated by Django 6.0.1 on 2026-01-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='current_location',
            field=models.CharField(choices=[('Main Store', 'Main Store'), ('Pharmacy', 'Pharmacy'), ('Radiology', 'Radiology'), ('Lab', 'Lab'), ('Ward', 'Ward'), ('Morgue', 'Morgue')], default='Main Store', max_length=100),
        ),
    ]
