# Generated by Django 6.0.1 on 2026-01-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_triageentry_height_triageentry_weight'),
        ('inventory', '0004_inventoryrequest_inventoryacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjusted_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='home.departments'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='home.departments'),
        ),
    ]
