# Generated by Django 4.2.27 on 2026-02-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockadjustment_adjusted_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Drug Classes',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dispensing_unit',
            field=models.CharField(default='Unit', help_text='Smallest unit sold (e.g., Tablet, ml, Piece)', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_dispensed_as_whole',
            field=models.BooleanField(default=False, help_text='If true, item is only sold as a whole unit (e.g., a small box)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Consumable', 'Consumable'), ('General', 'General Supply')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='packaging_unit',
            field=models.CharField(blank=True, help_text="How it's bought (e.g., Box of 100)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, help_text='Number of dispensing units in one packaging unit'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price per dispensing unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., pieces, ml, mg, boxes', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('formulation', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Infusion', 'Infusion'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler')], max_length=50)),
                ('strength', models.CharField(help_text='e.g., 500mg, 125mg/5ml', max_length=100)),
                ('is_controlled', models.BooleanField(default=False)),
                ('drug_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='inventory.drugclass')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, help_text='e.g., Plastic, Glass, Latex', max_length=100, null=True)),
                ('is_sterile', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, help_text='e.g., 5ml, 21G, Medium', max_length=50, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_detail', to='inventory.inventoryitem')),
            ],
        ),
    ]
