# Generated by Django 4.2.27 on 2026-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_drugclass_inventoryitem_dispensing_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='dispensing_unit',
            field=models.CharField(help_text='Smallest unit sold (e.g., Tablet, ml, Piece)', max_length=50),
        ),
    ]
