# Generated by Django 6.0.1 on 2026-02-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_dispensing_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='packaging_unit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='units_per_pack',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='is_controlled',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='strength',
        ),
    ]
