# Generated by Django 6.0.1 on 2026-02-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per dispensing unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum stock level before reordering'),
        ),
    ]
