# Generated by Django 6.0.1 on 2026-02-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_prescriptionitem_duration_days_and_more'),
        ('inventory', '0009_inventoryitem_buying_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity Dispensed')),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to='home.departments')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_items', to='inventory.inventoryitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_items', to='home.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to='home.visit')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryAcknowledgement',
        ),
    ]
