# Generated by Django 6.0.1 on 2026-02-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_delete_serviceparameters'),
        ('inventory', '0011_inventoryacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='purchase_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_records', to='accounts.inventorypurchase'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='receiving_notes',
            field=models.TextField(blank=True, help_text='Notes on condition during receipt', null=True),
        ),
    ]
