from django.urls import path

from . import views

app_name = 'hr'

urlpatterns = [
    path('', views.hr_dashboard, name='dashboard'),
    path('salaries/', views.salary_list, name='salary_list'),
    path('salaries/bulk-payroll-preview/', views.bulk_payroll_preview, name='bulk_payroll_preview'),
    path('salaries/payroll-run/', views.payroll_run_detail, name='payroll_run_detail'),
    path('salaries/<int:user_id>/', views.salary_edit, name='salary_edit'),
    path('leave/', views.leave_list, name='leave_list'),
    path('leave/apply/', views.leave_create, name='leave_create'),
    path('leave/<int:pk>/edit/', views.leave_edit, name='leave_edit'),
    path('leave/balance/', views.leave_balance_json, name='leave_balance_json'),
    path('leave/<int:pk>/', views.leave_detail, name='leave_detail'),
    path('leave/<int:pk>/approve/', views.leave_approve, name='leave_approve'),
    path('leave/<int:pk>/reject/', views.leave_reject, name='leave_reject'),
    path('leave/<int:pk>/cancel/', views.leave_cancel, name='leave_cancel'),
    path('off-days/', views.off_day_list, name='off_day_list'),
    path('off-days/queue/', views.off_day_queue, name='off_day_queue'),
    path('off-days/holidays/add/', views.holiday_create, name='holiday_create'),
    path('off-days/holidays/<int:pk>/', views.holiday_detail, name='holiday_detail'),
    path('off-days/holidays/<int:pk>/edit/', views.holiday_edit, name='holiday_edit'),
    path('off-days/staff/add/', views.staff_off_create, name='staff_off_create'),
    path('off-days/staff/<int:pk>/', views.staff_off_detail, name='staff_off_detail'),
    path('off-days/staff/<int:pk>/approve/', views.staff_off_approve, name='staff_off_approve'),
    path('off-days/staff/<int:pk>/reject/', views.staff_off_reject, name='staff_off_reject'),
    path('off-days/staff/<int:pk>/cancel/', views.staff_off_cancel, name='staff_off_cancel'),
    path('off-days/staff/<int:pk>/delete/', views.staff_off_delete, name='staff_off_delete'),
    path('off-days/holidays/<int:pk>/delete/', views.holiday_delete, name='holiday_delete'),
    path('settings/leave-types/', views.leave_type_list, name='leave_type_list'),
    path('settings/leave-types/add/', views.leave_type_create, name='leave_type_create'),
    path('settings/leave-types/<int:pk>/edit/', views.leave_type_edit, name='leave_type_edit'),
    path('settings/entitlements/<int:user_id>/', views.staff_entitlement_edit, name='staff_entitlement_edit'),
    path('attendance/', views.attendance_dashboard, name='attendance_dashboard'),
    path('attendance/staff/<int:user_id>/', views.attendance_user_detail, name='attendance_user_detail'),
    path('attendance/logs/', views.attendance_logs, name='attendance_logs'),
    path('attendance/manual/', views.attendance_manual, name='attendance_manual'),
    path('attendance/profiles/', views.attendance_profiles, name='attendance_profiles'),
    path('attendance/profiles/<int:user_id>/', views.attendance_profile_edit, name='attendance_profile_edit'),
    path('attendance/devices/', views.attendance_devices, name='attendance_devices'),
    path('attendance/devices/add/', views.attendance_device_create, name='attendance_device_create'),
    path('attendance/devices/<int:pk>/edit/', views.attendance_device_edit, name='attendance_device_edit'),
    path('attendance/devices/<int:pk>/sync/', views.attendance_device_sync, name='attendance_device_sync'),
    path('attendance/sync/', views.attendance_sync_all, name='attendance_sync_all'),
    path('attendance/<int:pk>/reprocess/', views.attendance_reprocess, name='attendance_reprocess'),
]
