# Generated by Django 4.2.27 on 2026-01-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_type', models.CharField(choices=[('IN-PATIENT', 'In-Patient'), ('OUT-PATIENT', 'Out-Patient')], max_length=20)),
                ('visit_mode', models.CharField(choices=[('Appointment', 'Appointment'), ('Walk In', 'Walk In')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TriageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EMERGENCY', 'Emergency'), ('PEDIATRIC', 'Pediatric'), ('MATERNITY', 'Maternity'), ('SURGERY', 'Surgery'), ('CARDIAC', 'Cardiac'), ('NEURO', 'Neurological'), ('RESPIRATORY', 'Respiratory'), ('ORTHOPEDIC', 'Orthopedic'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate (bpm)', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Respiratory rate (breaths/min)', null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='O2 saturation (%)', null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='Blood glucose (mg/dL)', max_digits=5, null=True)),
                ('triage_notes', models.TextField(blank=True, help_text='Triage nurse assessment notes')),
                ('disposition', models.CharField(blank=True, help_text="Disposition (e.g., 'Send to Emergency Room')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triage_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_entries', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_entries', to='home.visit')),
            ],
            options={
                'verbose_name': 'Triage Entry',
                'verbose_name_plural': 'Triage Entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qued_from', models.CharField(choices=[('triage', 'Triage'), ('consultation', 'Consultation')], max_length=20)),
                ('sent_to', models.CharField(choices=[('triage', 'Triage'), ('consultation', 'Consultation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_queue_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_queue_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_queue', to='home.visit')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='home.consultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_notes_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_notes_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='home.visit'),
        ),
    ]
