# Generated by Django 4.2.27 on 2026-01-27 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_consultation_visit_triageentry_patientque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_hod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='patientque',
            name='qued_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_from_queue', to='home.departments'),
        ),
        migrations.AlterField(
            model_name='patientque',
            name='sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_queue', to='home.departments'),
        ),
    ]
