# Generated by Django 4.2.27 on 2026-01-28 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_departments_alter_patientque_qued_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Emergency contact person name', max_length=200)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('UNCLE_AUNT', 'Uncle/Aunt'), ('COUSIN', 'Cousin'), ('FRIEND', 'Friend'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], help_text='Relationship to patient', max_length=20)),
                ('phone', models.CharField(help_text='Emergency contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Emergency contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Emergency contact address')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary emergency contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contacts_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='home.patient')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
