# Generated by Django 6.0.1 on 2026-01-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageentry',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height (cm)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='triageentry',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight (kg)', max_digits=5, null=True),
        ),
    ]
