# Generated by Django 6.0.1 on 2026-01-29 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_triageentry_height_triageentry_weight'),
        ('inventory', '0005_stockadjustment_adjusted_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(help_text='Reason for prescription')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or notes')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='home.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='home.visit')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily, Every 6 hours', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days, 2 weeks', max_length=100)),
                ('quantity', models.IntegerField(help_text='Total quantity to dispense')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for this medication')),
                ('dispensed', models.BooleanField(default=False, help_text='Has this been dispensed by pharmacy?')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_dispensed', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='inventory.inventoryitem')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
    ]
