# Generated by Django 6.0.1 on 2026-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_patient_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientque',
            name='queue_type',
            field=models.CharField(choices=[('INITIAL', 'New Visit'), ('REVIEW', 'Results Review')], default='INITIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='patientque',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
