# Generated by Django 6.0.1 on 2026-02-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_supplierinvoice_alter_inventorypurchase_options_and_more'),
        ('home', '0008_patientque_queue_type_patientque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='accounts.invoice'),
        ),
    ]
