# Generated by Django 4.2.27 on 2026-02-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_prescription_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='frequency',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dose_count',
            field=models.PositiveIntegerField(default=1, help_text='Units per dose (e.g., 2 tablets)'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Total days (e.g., 7 days)'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency_count',
            field=models.PositiveIntegerField(default=1, help_text='Times per day (e.g., 3 times)'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.IntegerField(help_text='Total units to dispense'),
        ),
    ]
