# Generated by Django 6.0.1 on 2026-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_prescriptionitem_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
