# Generated by Django 6.0.1 on 2026-02-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_diagnosis_impression_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='frequency_count',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Thrice Daily', 'Thrice Daily'), ('Four Times Daily', 'Four Times Daily'), ('Every 6 Hours', 'Every 6 Hours'), ('Every 8 Hours', 'Every 8 Hours'), ('Every 12 Hours', 'Every 12 Hours'), ('Every 24 Hours', 'Every 24 Hours'), ('As Needed', 'As Needed')], default='Once Daily', help_text='Frequency of medication', max_length=20),
        ),
    ]
