# Generated by Django 6.0.1 on 2026-02-12 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_prescriptionitem_duration_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(help_text='Where the patient is being referred to (Hospital/Clinic Name)', max_length=255)),
                ('reason', models.TextField(help_text='Reason for referral')),
                ('clinical_summary', models.TextField(blank=True, help_text='Summary of clinical findings')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the receiving doctor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='home.visit')),
            ],
        ),
    ]
