# Generated by Django 6.0.1 on 2026-01-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoice_invoiceitem_payment_service'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.invoice'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.service'),
        ),
    ]
