# Generated by Django 6.0.1 on 2026-01-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_service_options_service_department_and_more'),
        ('lab', '0002_alter_labresult_invoice_alter_labresult_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.invoiceitem'),
        ),
    ]
