# Generated by Django 4.2.27 on 2026-01-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_labresult_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/%Y/%m/'),
        ),
    ]
