# Generated by Django 6.0.1 on 2026-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_labreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='specimen',
            field=models.CharField(blank=True, choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Stool', 'Stool'), ('Sputum', 'Sputum'), ('Swab', 'Swab'), ('Tissue', 'Tissue'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
