# Generated by Django 6.0.1 on 2026-02-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_ambulancecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('ranges', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.labresult')),
            ],
        ),
    ]
