# Generated by Django 6.0.1 on 2026-02-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_ambulanceactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulanceactivity',
            name='amount',
        ),
    ]
