# Generated by Django 6.0.1 on 2026-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_remove_ambulanceactivity_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceactivity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
